// Lista de países con códigos de teléfono
const countries = [
  { code: '+54', name: 'Argentina' },
  { code: '+1', name: 'Estados Unidos' },
  { code: '+55', name: 'Brasil' },
  { code: '+56', name: 'Chile' },
  { code: '+57', name: 'Colombia' },
  { code: '+52', name: 'México' },
  { code: '+34', name: 'España' },
  { code: '+33', name: 'Francia' },
  { code: '+49', name: 'Alemania' },
  { code: '+44', name: 'Reino Unido' },
  { code: '+39', name: 'Italia' },
  { code: '+351', name: 'Portugal' },
  { code: '+31', name: 'Países Bajos' },
  { code: '+46', name: 'Suecia' },
  { code: '+47', name: 'Noruega' },
  { code: '+45', name: 'Dinamarca' },
  { code: '+41', name: 'Suiza' },
  { code: '+43', name: 'Austria' },
  { code: '+32', name: 'Bélgica' },
  { code: '+353', name: 'Irlanda' },
  { code: '+358', name: 'Finlandia' },
  { code: '+30', name: 'Grecia' },
  { code: '+48', name: 'Polonia' },
  { code: '+420', name: 'República Checa' },
  { code: '+421', name: 'Eslovaquia' },
  { code: '+36', name: 'Hungría' },
  { code: '+40', name: 'Rumania' },
  { code: '+359', name: 'Bulgaria' },
  { code: '+385', name: 'Croacia' },
  { code: '+386', name: 'Eslovenia' },
  { code: '+372', name: 'Estonia' },
  { code: '+371', name: 'Letonia' },
  { code: '+370', name: 'Lituania' },
  { code: '+7', name: 'Rusia' },
  { code: '+380', name: 'Ucrania' },
  { code: '+375', name: 'Bielorrusia' },
  { code: '+81', name: 'Japón' },
  { code: '+82', name: 'Corea del Sur' },
  { code: '+86', name: 'China' },
  { code: '+852', name: 'Hong Kong' },
  { code: '+853', name: 'Macao' },
  { code: '+886', name: 'Taiwán' },
  { code: '+65', name: 'Singapur' },
  { code: '+60', name: 'Malasia' },
  { code: '+66', name: 'Tailandia' },
  { code: '+84', name: 'Vietnam' },
  { code: '+63', name: 'Filipinas' },
  { code: '+62', name: 'Indonesia' },
  { code: '+91', name: 'India' },
  { code: '+92', name: 'Pakistán' },
  { code: '+880', name: 'Bangladesh' },
  { code: '+94', name: 'Sri Lanka' },
  { code: '+977', name: 'Nepal' },
  { code: '+975', name: 'Bután' },
  { code: '+960', name: 'Maldivas' },
  { code: '+20', name: 'Egipto' },
  { code: '+27', name: 'Sudáfrica' },
  { code: '+234', name: 'Nigeria' },
  { code: '+254', name: 'Kenia' },
  { code: '+256', name: 'Uganda' },
  { code: '+250', name: 'Ruanda' },
  { code: '+255', name: 'Tanzania' },
  { code: '+251', name: 'Etiopía' },
  { code: '+212', name: 'Marruecos' },
  { code: '+213', name: 'Argelia' },
  { code: '+216', name: 'Túnez' },
  { code: '+218', name: 'Libia' },
  { code: '+220', name: 'Gambia' },
  { code: '+221', name: 'Senegal' },
  { code: '+222', name: 'Mauritania' },
  { code: '+223', name: 'Mali' },
  { code: '+224', name: 'Guinea' },
  { code: '+225', name: 'Costa de Marfil' },
  { code: '+226', name: 'Burkina Faso' },
  { code: '+227', name: 'Níger' },
  { code: '+228', name: 'Togo' },
  { code: '+229', name: 'Benín' },
  { code: '+230', name: 'Mauricio' },
  { code: '+231', name: 'Liberia' },
  { code: '+232', name: 'Sierra Leona' },
  { code: '+233', name: 'Ghana' },
  { code: '+235', name: 'Chad' },
  { code: '+236', name: 'República Centroafricana' },
  { code: '+237', name: 'Camerún' },
  { code: '+238', name: 'Cabo Verde' },
  { code: '+239', name: 'Santo Tomé y Príncipe' },
  { code: '+240', name: 'Guinea Ecuatorial' },
  { code: '+241', name: 'Gabón' },
  { code: '+242', name: 'República del Congo' },
  { code: '+243', name: 'República Democrática del Congo' },
  { code: '+244', name: 'Angola' },
  { code: '+245', name: 'Guinea-Bisáu' },
  { code: '+246', name: 'Territorio Británico del Océano Índico' },
  { code: '+247', name: 'Isla Ascensión' },
  { code: '+248', name: 'Seychelles' },
  { code: '+249', name: 'Sudán' },
  { code: '+252', name: 'Somalia' },
  { code: '+253', name: 'Yibuti' },
  { code: '+257', name: 'Burundi' },
  { code: '+258', name: 'Mozambique' },
  { code: '+260', name: 'Zambia' },
  { code: '+261', name: 'Madagascar' },
  { code: '+262', name: 'Reunión' },
  { code: '+263', name: 'Zimbabue' },
  { code: '+264', name: 'Namibia' },
  { code: '+265', name: 'Malaui' },
  { code: '+266', name: 'Lesoto' },
  { code: '+267', name: 'Botsuana' },
  { code: '+268', name: 'Suazilandia' },
  { code: '+269', name: 'Comoras' },
  { code: '+290', name: 'Santa Elena' },
  { code: '+291', name: 'Eritrea' },
  { code: '+297', name: 'Aruba' },
  { code: '+298', name: 'Islas Feroe' },
  { code: '+299', name: 'Groenlandia' },
  { code: '+350', name: 'Gibraltar' },
  { code: '+352', name: 'Luxemburgo' },
  { code: '+354', name: 'Islandia' },
  { code: '+355', name: 'Albania' },
  { code: '+356', name: 'Malta' },
  { code: '+357', name: 'Chipre' },
  { code: '+373', name: 'Moldavia' },
  { code: '+374', name: 'Armenia' },
  { code: '+376', name: 'Andorra' },
  { code: '+377', name: 'Mónaco' },
  { code: '+378', name: 'San Marino' },
  { code: '+381', name: 'Serbia' },
  { code: '+382', name: 'Montenegro' },
  { code: '+383', name: 'Kosovo' },
  { code: '+387', name: 'Bosnia y Herzegovina' },
  { code: '+389', name: 'Macedonia del Norte' },
  { code: '+423', name: 'Liechtenstein' },
  { code: '+500', name: 'Islas Malvinas' },
  { code: '+501', name: 'Belice' },
  { code: '+502', name: 'Guatemala' },
  { code: '+503', name: 'El Salvador' },
  { code: '+504', name: 'Honduras' },
  { code: '+505', name: 'Nicaragua' },
  { code: '+506', name: 'Costa Rica' },
  { code: '+507', name: 'Panamá' },
  { code: '+508', name: 'San Pedro y Miquelón' },
  { code: '+509', name: 'Haití' },
  { code: '+590', name: 'Guadalupe' },
  { code: '+591', name: 'Bolivia' },
  { code: '+592', name: 'Guyana' },
  { code: '+593', name: 'Ecuador' },
  { code: '+594', name: 'Guayana Francesa' },
  { code: '+595', name: 'Paraguay' },
  { code: '+596', name: 'Martinica' },
  { code: '+597', name: 'Surinam' },
  { code: '+598', name: 'Uruguay' },
  { code: '+599', name: 'Antillas Neerlandesas' },
  { code: '+670', name: 'Timor Oriental' },
  { code: '+672', name: 'Antártida' },
  { code: '+673', name: 'Brunéi' },
  { code: '+674', name: 'Nauru' },
  { code: '+675', name: 'Papúa Nueva Guinea' },
  { code: '+676', name: 'Tonga' },
  { code: '+677', name: 'Islas Salomón' },
  { code: '+678', name: 'Vanuatu' },
  { code: '+679', name: 'Fiyi' },
  { code: '+680', name: 'Palau' },
  { code: '+681', name: 'Wallis y Futuna' },
  { code: '+682', name: 'Islas Cook' },
  { code: '+683', name: 'Niue' },
  { code: '+684', name: 'Samoa Americana' },
  { code: '+685', name: 'Samoa' },
  { code: '+686', name: 'Kiribati' },
  { code: '+687', name: 'Nueva Caledonia' },
  { code: '+688', name: 'Tuvalu' },
  { code: '+689', name: 'Polinesia Francesa' },
  { code: '+690', name: 'Tokelau' },
  { code: '+691', name: 'Micronesia' },
  { code: '+692', name: 'Islas Marshall' },
  { code: '+850', name: 'Corea del Norte' },
  { code: '+855', name: 'Camboya' },
  { code: '+856', name: 'Laos' },
  { code: '+961', name: 'Líbano' },
  { code: '+962', name: 'Jordania' },
  { code: '+963', name: 'Siria' },
  { code: '+964', name: 'Irak' },
  { code: '+965', name: 'Kuwait' },
  { code: '+966', name: 'Arabia Saudí' },
  { code: '+967', name: 'Yemen' },
  { code: '+968', name: 'Omán' },
  { code: '+970', name: 'Palestina' },
  { code: '+971', name: 'Emiratos Árabes Unidos' },
  { code: '+972', name: 'Israel' },
  { code: '+973', name: 'Baréin' },
  { code: '+974', name: 'Catar' },
  { code: '+976', name: 'Mongolia' },
  { code: '+992', name: 'Tayikistán' },
  { code: '+993', name: 'Turkmenistán' },
  { code: '+994', name: 'Azerbaiyán' },
  { code: '+995', name: 'Georgia' },
  { code: '+996', name: 'Kirguistán' },
  { code: '+998', name: 'Uzbekistán' }
];

// Función para generar las opciones del select
function generateCountryOptions() {
  // Ordenar países alfabéticamente por nombre, pero mantener Argentina al principio
  const sortedCountries = countries.sort((a, b) => {
    if (a.code === '+54') return -1; // Argentina siempre primero
    if (b.code === '+54') return 1;
    return a.name.localeCompare(b.name, 'es'); // Ordenar alfabéticamente en español
  });
  
  return sortedCountries.map(country => 
    `<option value="${country.code}">${country.name} ${country.code}</option>`
  ).join('');
}

// Exportar para uso en otros archivos
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { countries, generateCountryOptions };
}
